# Generated by Django 4.2.5 on 2023-10-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project.', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Projects start time.')),
                ('completion_time', models.DateTimeField(help_text='Projects end time', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the task.', max_length=20)),
                ('description', models.TextField(help_text='The description of task.')),
                ('complete_status', models.CharField(choices=[('NOT_START', 'Not start'), ('IN_WORKING', 'In working'), ('DONE', 'Done')], default='NOT_START', help_text='Task completion status.', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Time when task was created.')),
                ('planned_end_task', models.DateTimeField(help_text='Planned end time of task.')),
                ('end_time', models.DateTimeField(help_text='Time of the end of task', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
